"""Schema-aware API fuzzing.

The endpoint list comes from the app's own OpenAPI document (served nowhere --
`openapi_url` is off -- but still generated by FastAPI), so a new route is fuzzed
the day it is added. Every route is hit with hostile bodies, odd content types,
hostile headers and cookies. Invariants: never a 5xx, never a traceback or a
file path in the body, always the security headers, never a persistent session
created by a rejected request."""

import json
import re

import pytest
from fastapi.testclient import TestClient
from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st

import main
from firebase_helpers import make_token

SETTINGS = settings(max_examples=60, deadline=None, suppress_health_check=[HealthCheck.too_slow, HealthCheck.function_scoped_fixture])

OPERATIONS = sorted(
    (method.upper(), path)
    for path, item in main.app.openapi()["paths"].items()
    for method in item
    if method in ("get", "post", "put", "delete", "patch")
)
SKIP = {("POST", "/api/ask/stream")}  # server-sent events: covered separately below (it streams)

json_values = st.recursive(
    st.none() | st.booleans() | st.integers() | st.floats(allow_nan=False, allow_infinity=False) | st.text(max_size=40),
    lambda c: st.lists(c, max_size=4) | st.dictionaries(st.text(max_size=12), c, max_size=5),
    max_leaves=15,
)
bodies = st.one_of(
    json_values.map(lambda v: json.dumps(v).encode()),
    st.binary(max_size=3000),
    st.just(b""),
    st.sampled_from([b"{", b"[", b'{"question": "' + b"a" * 20000 + b'"}', b'{"id": ' + b"9" * 400 + b"}", b'{"doc_ids": ' + b"[" * 500 + b"]" * 500 + b"}"]),
)
content_types = st.sampled_from(["application/json", "text/plain", "application/x-www-form-urlencoded", "multipart/form-data", "application/xml", "", "application/json; charset=utf-16"])
odd_headers = st.dictionaries(
    st.sampled_from(["X-Forwarded-For", "X-Real-IP", "X-Forwarded-Proto", "Host", "Origin", "Referer", "Sec-Fetch-Site", "Authorization", "X-Request-ID", "Content-Length", "Transfer-Encoding", "Accept", "User-Agent"]),
    st.text(alphabet=st.characters(min_codepoint=32, max_codepoint=126), max_size=80),
    max_size=4,
)
cookies = st.dictionaries(st.sampled_from(["session_id", "__Host-session", "auth_id", "__Host-auth", "x"]), st.text(alphabet=st.characters(min_codepoint=33, max_codepoint=126, blacklist_characters=";, \"\\"), max_size=80), max_size=3)


def check(response):
    not_configured = response.status_code == 503 and response.json().get("error") == "Sign-in is not configured on this server."
    assert response.status_code < 500 or not_configured, (response.status_code, response.text[:200])  # (503 is the documented "sign-in is off" answer)
    text = response.text
    assert "Traceback" not in text and not re.search(r"[A-Za-z]:\\\\|/srv/|/home/|site-packages", text)
    for header in ("content-security-policy", "x-content-type-options", "x-frame-options"):
        assert header in response.headers


@pytest.fixture(scope="module")
def client():
    with TestClient(main.app, raise_server_exceptions=False) as c:
        yield c


@pytest.mark.parametrize("method,path", [op for op in OPERATIONS if op not in SKIP])
@SETTINGS
@given(data=st.data())
def test_no_route_returns_a_server_error_for_hostile_requests(client, method, path, data):
    body = data.draw(bodies)
    headers = {k: v for k, v in data.draw(odd_headers).items() if k.lower() not in ("host", "content-length", "transfer-encoding")}
    ctype = data.draw(content_types)
    if ctype:
        headers["Content-Type"] = ctype
    client.cookies.clear()
    for name, value in data.draw(cookies).items():
        client.cookies.set(name, value)
    check(client.request(method, path, content=body if method != "GET" else None, headers=headers))


@SETTINGS
@given(name=st.text(max_size=300), body=st.binary(max_size=4000), ctype=st.sampled_from(["application/pdf", "text/plain", "application/octet-stream", "", "image/png"]))
def test_the_upload_endpoint_survives_any_file(client, name, body, ctype):
    client.cookies.clear()
    check(client.post("/api/ingest", files={"file": (name, body, ctype)}))


@SETTINGS
@given(st.text(alphabet=st.characters(min_codepoint=32, max_codepoint=126), max_size=300))
def test_the_upload_endpoint_survives_odd_multipart_field_names(client, field):
    client.cookies.clear()
    check(client.post("/api/ingest", files={field or "x": ("a.txt", b"hello planets", "text/plain")}))


@SETTINGS
@given(question=st.text(max_size=1500), doc_ids=st.one_of(st.none(), st.lists(st.text(max_size=30), max_size=5)))
def test_the_streaming_endpoint_never_errors_without_a_document(client, question, doc_ids):
    client.cookies.clear()
    r = client.post("/api/ask/stream", json={"question": question, "doc_ids": doc_ids})
    check(r)
    assert r.status_code in (400, 429)  # no document is loaded (or the rate limit says wait): a clean refusal, never a 500


@pytest.mark.usefixtures("signin_on")
@SETTINGS
@given(token=st.one_of(json_values, st.text(max_size=5000)))
def test_the_login_endpoint_survives_any_token(client, token):
    client.cookies.clear()
    r = client.post("/api/login", json={"id_token": token})
    check(r)
    assert r.status_code in (401, 429, 400, 503) and "auth_id" not in r.cookies


def test_a_valid_token_still_works_after_all_that(client, signin_on):
    client.cookies.clear()
    r = client.post("/api/login", json={"id_token": make_token()})
    assert r.status_code in (200, 429)
